//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace Art.WebService.SmsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmsSoap", Namespace="http://tempuri.org/")]
    public partial class Sms : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsSaveLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoiceSendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsBaseSaveLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsBaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback MsgSendSmsSaveLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback MsgSendSmsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sms() {
            this.Url = global::Art.WebService.Properties.Settings.Default.Art_WebService_SmsService_Sms;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendSmsCompletedEventHandler SendSmsCompleted;
        
        /// <remarks/>
        public event SendSmsResultCompletedEventHandler SendSmsResultCompleted;
        
        /// <remarks/>
        public event SendSmsSaveLogCompletedEventHandler SendSmsSaveLogCompleted;
        
        /// <remarks/>
        public event VoiceSendSmsCompletedEventHandler VoiceSendSmsCompleted;
        
        /// <remarks/>
        public event SendSmsBaseSaveLogCompletedEventHandler SendSmsBaseSaveLogCompleted;
        
        /// <remarks/>
        public event SendSmsBaseCompletedEventHandler SendSmsBaseCompleted;
        
        /// <remarks/>
        public event MsgSendSmsSaveLogCompletedEventHandler MsgSendSmsSaveLogCompleted;
        
        /// <remarks/>
        public event MsgSendSmsCompletedEventHandler MsgSendSmsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSms(string Mobile, string Content) {
            object[] results = this.Invoke("SendSms", new object[] {
                        Mobile,
                        Content});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsAsync(string Mobile, string Content) {
            this.SendSmsAsync(Mobile, Content, null);
        }
        
        /// <remarks/>
        public void SendSmsAsync(string Mobile, string Content, object userState) {
            if ((this.SendSmsOperationCompleted == null)) {
                this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
            }
            this.InvokeAsync("SendSms", new object[] {
                        Mobile,
                        Content}, this.SendSmsOperationCompleted, userState);
        }
        
        private void OnSendSmsOperationCompleted(object arg) {
            if ((this.SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSmsResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSmsResult(string Mobile, string Content) {
            object[] results = this.Invoke("SendSmsResult", new object[] {
                        Mobile,
                        Content});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsResultAsync(string Mobile, string Content) {
            this.SendSmsResultAsync(Mobile, Content, null);
        }
        
        /// <remarks/>
        public void SendSmsResultAsync(string Mobile, string Content, object userState) {
            if ((this.SendSmsResultOperationCompleted == null)) {
                this.SendSmsResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsResultOperationCompleted);
            }
            this.InvokeAsync("SendSmsResult", new object[] {
                        Mobile,
                        Content}, this.SendSmsResultOperationCompleted, userState);
        }
        
        private void OnSendSmsResultOperationCompleted(object arg) {
            if ((this.SendSmsResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsResultCompleted(this, new SendSmsResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSmsSaveLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSmsSaveLog(string mobile, string content, string smsSource, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> supplierID, bool isVoiceSms) {
            object[] results = this.Invoke("SendSmsSaveLog", new object[] {
                        mobile,
                        content,
                        smsSource,
                        supplierID,
                        isVoiceSms});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsSaveLogAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            this.SendSmsSaveLogAsync(mobile, content, smsSource, supplierID, isVoiceSms, null);
        }
        
        /// <remarks/>
        public void SendSmsSaveLogAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms, object userState) {
            if ((this.SendSmsSaveLogOperationCompleted == null)) {
                this.SendSmsSaveLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsSaveLogOperationCompleted);
            }
            this.InvokeAsync("SendSmsSaveLog", new object[] {
                        mobile,
                        content,
                        smsSource,
                        supplierID,
                        isVoiceSms}, this.SendSmsSaveLogOperationCompleted, userState);
        }
        
        private void OnSendSmsSaveLogOperationCompleted(object arg) {
            if ((this.SendSmsSaveLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsSaveLogCompleted(this, new SendSmsSaveLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoiceSendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VoiceSendSms(string mobile, string content, string smsSource, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> supplierID) {
            object[] results = this.Invoke("VoiceSendSms", new object[] {
                        mobile,
                        content,
                        smsSource,
                        supplierID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VoiceSendSmsAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            this.VoiceSendSmsAsync(mobile, content, smsSource, supplierID, null);
        }
        
        /// <remarks/>
        public void VoiceSendSmsAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, object userState) {
            if ((this.VoiceSendSmsOperationCompleted == null)) {
                this.VoiceSendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoiceSendSmsOperationCompleted);
            }
            this.InvokeAsync("VoiceSendSms", new object[] {
                        mobile,
                        content,
                        smsSource,
                        supplierID}, this.VoiceSendSmsOperationCompleted, userState);
        }
        
        private void OnVoiceSendSmsOperationCompleted(object arg) {
            if ((this.VoiceSendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoiceSendSmsCompleted(this, new VoiceSendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSmsBaseSaveLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSmsBaseSaveLog(string mobile, string content, SmsSendType type, string smsSource, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> supplierID) {
            object[] results = this.Invoke("SendSmsBaseSaveLog", new object[] {
                        mobile,
                        content,
                        type,
                        smsSource,
                        supplierID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsBaseSaveLogAsync(string mobile, string content, SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            this.SendSmsBaseSaveLogAsync(mobile, content, type, smsSource, supplierID, null);
        }
        
        /// <remarks/>
        public void SendSmsBaseSaveLogAsync(string mobile, string content, SmsSendType type, string smsSource, System.Nullable<int> supplierID, object userState) {
            if ((this.SendSmsBaseSaveLogOperationCompleted == null)) {
                this.SendSmsBaseSaveLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsBaseSaveLogOperationCompleted);
            }
            this.InvokeAsync("SendSmsBaseSaveLog", new object[] {
                        mobile,
                        content,
                        type,
                        smsSource,
                        supplierID}, this.SendSmsBaseSaveLogOperationCompleted, userState);
        }
        
        private void OnSendSmsBaseSaveLogOperationCompleted(object arg) {
            if ((this.SendSmsBaseSaveLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsBaseSaveLogCompleted(this, new SendSmsBaseSaveLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSmsBase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSmsBase(string Mobile, string Content, SmsSendType type) {
            object[] results = this.Invoke("SendSmsBase", new object[] {
                        Mobile,
                        Content,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsBaseAsync(string Mobile, string Content, SmsSendType type) {
            this.SendSmsBaseAsync(Mobile, Content, type, null);
        }
        
        /// <remarks/>
        public void SendSmsBaseAsync(string Mobile, string Content, SmsSendType type, object userState) {
            if ((this.SendSmsBaseOperationCompleted == null)) {
                this.SendSmsBaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsBaseOperationCompleted);
            }
            this.InvokeAsync("SendSmsBase", new object[] {
                        Mobile,
                        Content,
                        type}, this.SendSmsBaseOperationCompleted, userState);
        }
        
        private void OnSendSmsBaseOperationCompleted(object arg) {
            if ((this.SendSmsBaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsBaseCompleted(this, new SendSmsBaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MsgSendSmsSaveLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MsgSendSmsSaveLog(string mobile, string content, SmsSendType type, string smsSource, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> supplierID) {
            object[] results = this.Invoke("MsgSendSmsSaveLog", new object[] {
                        mobile,
                        content,
                        type,
                        smsSource,
                        supplierID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MsgSendSmsSaveLogAsync(string mobile, string content, SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            this.MsgSendSmsSaveLogAsync(mobile, content, type, smsSource, supplierID, null);
        }
        
        /// <remarks/>
        public void MsgSendSmsSaveLogAsync(string mobile, string content, SmsSendType type, string smsSource, System.Nullable<int> supplierID, object userState) {
            if ((this.MsgSendSmsSaveLogOperationCompleted == null)) {
                this.MsgSendSmsSaveLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMsgSendSmsSaveLogOperationCompleted);
            }
            this.InvokeAsync("MsgSendSmsSaveLog", new object[] {
                        mobile,
                        content,
                        type,
                        smsSource,
                        supplierID}, this.MsgSendSmsSaveLogOperationCompleted, userState);
        }
        
        private void OnMsgSendSmsSaveLogOperationCompleted(object arg) {
            if ((this.MsgSendSmsSaveLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MsgSendSmsSaveLogCompleted(this, new MsgSendSmsSaveLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MsgSendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MsgSendSms(string mobile, string content) {
            object[] results = this.Invoke("MsgSendSms", new object[] {
                        mobile,
                        content});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MsgSendSmsAsync(string mobile, string content) {
            this.MsgSendSmsAsync(mobile, content, null);
        }
        
        /// <remarks/>
        public void MsgSendSmsAsync(string mobile, string content, object userState) {
            if ((this.MsgSendSmsOperationCompleted == null)) {
                this.MsgSendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMsgSendSmsOperationCompleted);
            }
            this.InvokeAsync("MsgSendSms", new object[] {
                        mobile,
                        content}, this.MsgSendSmsOperationCompleted, userState);
        }
        
        private void OnMsgSendSmsOperationCompleted(object arg) {
            if ((this.MsgSendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MsgSendSmsCompleted(this, new MsgSendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SmsSendType {
        
        /// <remarks/>
        亿美软通,
        
        /// <remarks/>
        营销渠道,
        
        /// <remarks/>
        天润融通,
        
        /// <remarks/>
        百分通联,
        
        /// <remarks/>
        云信,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendSmsResultCompletedEventHandler(object sender, SendSmsResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendSmsSaveLogCompletedEventHandler(object sender, SendSmsSaveLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsSaveLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsSaveLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void VoiceSendSmsCompletedEventHandler(object sender, VoiceSendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoiceSendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoiceSendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendSmsBaseSaveLogCompletedEventHandler(object sender, SendSmsBaseSaveLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsBaseSaveLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsBaseSaveLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendSmsBaseCompletedEventHandler(object sender, SendSmsBaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsBaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsBaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void MsgSendSmsSaveLogCompletedEventHandler(object sender, MsgSendSmsSaveLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MsgSendSmsSaveLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MsgSendSmsSaveLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void MsgSendSmsCompletedEventHandler(object sender, MsgSendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MsgSendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MsgSendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591