//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ets.SingleApi.ExternalServices.SmsSoap {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsSendType", Namespace="http://tempuri.org/")]
    public enum SmsSendType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        亿美软通 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        天下畅通 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        创世漫道 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        营销渠道 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsSoap.SmsSoap")]
    public interface SmsSoap {
        
        // CODEGEN: Generating message contract since element name Mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse SendSms(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse> SendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name Mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBase", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse SendSmsBase(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBase", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse> SendSmsBaseAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest request);
        
        // CODEGEN: Generating message contract since element name mobile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSms", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse MsgSendSms(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse> MsgSendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string Mobile, string Content) {
            this.Mobile = Mobile;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBase", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequestBody Body;
        
        public SendSmsBaseRequest() {
        }
        
        public SendSmsBaseRequest(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type;
        
        public SendSmsBaseRequestBody() {
        }
        
        public SendSmsBaseRequestBody(string Mobile, string Content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type) {
            this.Mobile = Mobile;
            this.Content = Content;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponseBody Body;
        
        public SendSmsBaseResponse() {
        }
        
        public SendSmsBaseResponse(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsBaseResult;
        
        public SendSmsBaseResponseBody() {
        }
        
        public SendSmsBaseResponseBody(string SendSmsBaseResult) {
            this.SendSmsBaseResult = SendSmsBaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequestBody Body;
        
        public MsgSendSmsRequest() {
        }
        
        public MsgSendSmsRequest(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public MsgSendSmsRequestBody() {
        }
        
        public MsgSendSmsRequestBody(string mobile, string content) {
            this.mobile = mobile;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponseBody Body;
        
        public MsgSendSmsResponse() {
        }
        
        public MsgSendSmsResponse(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgSendSmsResult;
        
        public MsgSendSmsResponseBody() {
        }
        
        public MsgSendSmsResponseBody(string MsgSendSmsResult) {
            this.MsgSendSmsResult = MsgSendSmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsSoapChannel : Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSoapClient : System.ServiceModel.ClientBase<Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap>, Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap {
        
        public SmsSoapClient() {
        }
        
        public SmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSms(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string Mobile, string Content) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse> SendSmsAsync(string Mobile, string Content) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsBase(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest request) {
            return base.Channel.SendSmsBase(request);
        }
        
        public string SendSmsBase(string Mobile, string Content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.type = type;
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsBase(inValue);
            return retVal.Body.SendSmsBaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsBaseAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest request) {
            return base.Channel.SendSmsBaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse> SendSmsBaseAsync(string Mobile, string Content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.type = type;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsBaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.MsgSendSms(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest request) {
            return base.Channel.MsgSendSms(request);
        }
        
        public string MsgSendSms(string mobile, string content) {
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).MsgSendSms(inValue);
            return retVal.Body.MsgSendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.MsgSendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest request) {
            return base.Channel.MsgSendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse> MsgSendSmsAsync(string mobile, string content) {
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).MsgSendSmsAsync(inValue);
        }
    }
}
