//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ets.SingleApi.ExternalServices.SmsSoap {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsSendType", Namespace="http://tempuri.org/")]
    public enum SmsSendType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        亿美软通 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        天下畅通 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        创世漫道 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        营销渠道 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        天润融通 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsSoap.SmsSoap")]
    public interface SmsSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse SendSms(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse> SendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLog", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogResponse SendSmsSaveLog(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogResponse> SendSmsSaveLogAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoiceSendSms", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsResponse VoiceSendSms(Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoiceSendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsResponse> VoiceSendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBaseSaveLog", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogResponse SendSmsBaseSaveLog(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBaseSaveLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogResponse> SendSmsBaseSaveLogAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBase", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse SendSmsBase(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBase", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse> SendSmsBaseAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSmsSaveLog", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogResponse MsgSendSmsSaveLog(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSmsSaveLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogResponse> MsgSendSmsSaveLogAsync(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSms", ReplyAction="*")]
        Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse MsgSendSms(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse> MsgSendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string Mobile, string Content) {
            this.Mobile = Mobile;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequestBody Body;
        
        public SendSmsSaveLogRequest() {
        }
        
        public SendSmsSaveLogRequest(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isVoiceSms;
        
        public SendSmsSaveLogRequestBody() {
        }
        
        public SendSmsSaveLogRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.isVoiceSms = isVoiceSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogResponseBody Body;
        
        public SendSmsSaveLogResponse() {
        }
        
        public SendSmsSaveLogResponse(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogResult;
        
        public SendSmsSaveLogResponseBody() {
        }
        
        public SendSmsSaveLogResponseBody(string SendSmsSaveLogResult) {
            this.SendSmsSaveLogResult = SendSmsSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VoiceSendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VoiceSendSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequestBody Body;
        
        public VoiceSendSmsRequest() {
        }
        
        public VoiceSendSmsRequest(Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VoiceSendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        public VoiceSendSmsRequestBody() {
        }
        
        public VoiceSendSmsRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VoiceSendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VoiceSendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsResponseBody Body;
        
        public VoiceSendSmsResponse() {
        }
        
        public VoiceSendSmsResponse(Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VoiceSendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VoiceSendSmsResult;
        
        public VoiceSendSmsResponseBody() {
        }
        
        public VoiceSendSmsResponseBody(string VoiceSendSmsResult) {
            this.VoiceSendSmsResult = VoiceSendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequestBody Body;
        
        public SendSmsBaseSaveLogRequest() {
        }
        
        public SendSmsBaseSaveLogRequest(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> supplierID;
        
        public SendSmsBaseSaveLogRequestBody() {
        }
        
        public SendSmsBaseSaveLogRequestBody(string mobile, string content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.type = type;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogResponseBody Body;
        
        public SendSmsBaseSaveLogResponse() {
        }
        
        public SendSmsBaseSaveLogResponse(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsBaseSaveLogResult;
        
        public SendSmsBaseSaveLogResponseBody() {
        }
        
        public SendSmsBaseSaveLogResponseBody(string SendSmsBaseSaveLogResult) {
            this.SendSmsBaseSaveLogResult = SendSmsBaseSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBase", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequestBody Body;
        
        public SendSmsBaseRequest() {
        }
        
        public SendSmsBaseRequest(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type;
        
        public SendSmsBaseRequestBody() {
        }
        
        public SendSmsBaseRequestBody(string Mobile, string Content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type) {
            this.Mobile = Mobile;
            this.Content = Content;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponseBody Body;
        
        public SendSmsBaseResponse() {
        }
        
        public SendSmsBaseResponse(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsBaseResult;
        
        public SendSmsBaseResponseBody() {
        }
        
        public SendSmsBaseResponseBody(string SendSmsBaseResult) {
            this.SendSmsBaseResult = SendSmsBaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequestBody Body;
        
        public MsgSendSmsSaveLogRequest() {
        }
        
        public MsgSendSmsSaveLogRequest(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> supplierID;
        
        public MsgSendSmsSaveLogRequestBody() {
        }
        
        public MsgSendSmsSaveLogRequestBody(string mobile, string content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.type = type;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogResponseBody Body;
        
        public MsgSendSmsSaveLogResponse() {
        }
        
        public MsgSendSmsSaveLogResponse(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgSendSmsSaveLogResult;
        
        public MsgSendSmsSaveLogResponseBody() {
        }
        
        public MsgSendSmsSaveLogResponseBody(string MsgSendSmsSaveLogResult) {
            this.MsgSendSmsSaveLogResult = MsgSendSmsSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSms", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequestBody Body;
        
        public MsgSendSmsRequest() {
        }
        
        public MsgSendSmsRequest(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public MsgSendSmsRequestBody() {
        }
        
        public MsgSendSmsRequestBody(string mobile, string content) {
            this.mobile = mobile;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponseBody Body;
        
        public MsgSendSmsResponse() {
        }
        
        public MsgSendSmsResponse(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgSendSmsResult;
        
        public MsgSendSmsResponseBody() {
        }
        
        public MsgSendSmsResponseBody(string MsgSendSmsResult) {
            this.MsgSendSmsResult = MsgSendSmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsSoapChannel : Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSoapClient : System.ServiceModel.ClientBase<Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap>, Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap {
        
        public SmsSoapClient() {
        }
        
        public SmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSms(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string Mobile, string Content) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsResponse> SendSmsAsync(string Mobile, string Content) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsSaveLog(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequest request) {
            return base.Channel.SendSmsSaveLog(request);
        }
        
        public string SendSmsSaveLog(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsSaveLog(inValue);
            return retVal.Body.SendSmsSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsSaveLogAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequest request) {
            return base.Channel.SendSmsSaveLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogResponse> SendSmsSaveLogAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsSaveLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.VoiceSendSms(Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequest request) {
            return base.Channel.VoiceSendSms(request);
        }
        
        public string VoiceSendSms(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).VoiceSendSms(inValue);
            return retVal.Body.VoiceSendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.VoiceSendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequest request) {
            return base.Channel.VoiceSendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsResponse> VoiceSendSmsAsync(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.VoiceSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).VoiceSendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsBaseSaveLog(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequest request) {
            return base.Channel.SendSmsBaseSaveLog(request);
        }
        
        public string SendSmsBaseSaveLog(string mobile, string content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsBaseSaveLog(inValue);
            return retVal.Body.SendSmsBaseSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsBaseSaveLogAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequest request) {
            return base.Channel.SendSmsBaseSaveLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogResponse> SendSmsBaseSaveLogAsync(string mobile, string content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsBaseSaveLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsBase(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest request) {
            return base.Channel.SendSmsBase(request);
        }
        
        public string SendSmsBase(string Mobile, string Content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.type = type;
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsBase(inValue);
            return retVal.Body.SendSmsBaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.SendSmsBaseAsync(Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest request) {
            return base.Channel.SendSmsBaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseResponse> SendSmsBaseAsync(string Mobile, string Content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type) {
            Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.SendSmsBaseRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.type = type;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).SendSmsBaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.MsgSendSmsSaveLog(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequest request) {
            return base.Channel.MsgSendSmsSaveLog(request);
        }
        
        public string MsgSendSmsSaveLog(string mobile, string content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).MsgSendSmsSaveLog(inValue);
            return retVal.Body.MsgSendSmsSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.MsgSendSmsSaveLogAsync(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequest request) {
            return base.Channel.MsgSendSmsSaveLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogResponse> MsgSendSmsSaveLogAsync(string mobile, string content, Ets.SingleApi.ExternalServices.SmsSoap.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).MsgSendSmsSaveLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.MsgSendSms(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest request) {
            return base.Channel.MsgSendSms(request);
        }
        
        public string MsgSendSms(string mobile, string content) {
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse retVal = ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).MsgSendSms(inValue);
            return retVal.Body.MsgSendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse> Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap.MsgSendSmsAsync(Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest request) {
            return base.Channel.MsgSendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsResponse> MsgSendSmsAsync(string mobile, string content) {
            Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest inValue = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequest();
            inValue.Body = new Ets.SingleApi.ExternalServices.SmsSoap.MsgSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            return ((Ets.SingleApi.ExternalServices.SmsSoap.SmsSoap)(this)).MsgSendSmsAsync(inValue);
        }
    }
}
